import md5 from 'blueimp-md5';

export const usuarios = [
	{ id: "u001", nome: "admin", senha: md5("1234") },
	{ id: "u002", nome: "diretor", senha: md5("senha123") },
]
export const clientes = [
	{id: "c1", nome: "Antonio Miguel Antonio", telefone: "845421639", email: "e@gmail.com", morada: "Bairro 5 Chimoio", data: "2025-02-02 00:00"},
	{id: "c2", nome: "Merdi Mutombo", telefone: "875421632", email: "r@gmail.com", morada: "Bairro 5 Chimoio", data: "2025-02-02 00:00"},
	{id: "c3", nome: "Albano Antonio", telefone: "875421633", email: "ew@gmail.com", morada: "Bairro 5 Chimoio", data: "2025-02-02 00:00"},
	{id: "c4", nome: "Albano Antonio", telefone: "875421633", email: "ew@gmail.com", morada: "Bairro 5 Chimoio", data: "2025-02-02 00:00"},
	{id: "c5", nome: "Manuel Antonio", telefone: "875421633", email: "ew@gmail.com", morada: "Bairro 5 Chimoio", data: "2025-02-02 00:00"},
]
export const parametros = [

	{ id: "Cn", categoria: "Agua", valor: 1100, campos: "x,y", formula: "x/y" },
	{ id: "Na", categoria: "Agua", valor: 500, campos: "x,y,z", formula: "x*y/z" },
	{ id: "Mg", categoria: "Agua", valor: 750, campos: "x,y,z", formula: "x/z + y" },
	{ id: "Zn", categoria: "Alimento", valor: 900, campos: "x,y,z", formula: "x*y/z" },
	{ id: "Pr", categoria: "Alimento", valor: 300, campos: "x,y,z", formula: "x - y * z" },
	{ id: "C", categoria: "Alimento", valor: 1200, campos: "x,y,z", formula: "x/y + z" },
	{ id: "He", categoria: "Agua e Alimento", valor: 1000, campos: "x,y,z", formula: "x/y*x/z" },
	{ id: "Fr", categoria: "Agua e Alimento", valor: 400, campos: "x,y,z", formula: "x - y * z" },
	{ id: "N", categoria: "Agua e Alimento", valor: 800, campos: "x,y,z", formula: "(x + y) / z" },
];

export const proformas = [
	{ id: "a11e", cliente: "c1", nome: "Analise de Agua", parametros: "Zn,Na,Mg", totalpagar: 1000, data: "2025-02-02 00:00", estado: "analisada" },
	{ id: "a111", cliente: "c3", nome: "Analise de Agua", parametros: "Na,Mg", totalpagar: 1000, data: "2025-02-02 00:00", estado: "analisada" },
	{ id: "a1e1", cliente: "c1", nome: "Analise de Alimentos", parametros: "C,Cc,Fr,N", totalpagar: 1000, data: "2025-02-02 00:00", estado: "analisada" },
	{ id: "a1e1e", cliente: "c4", nome: "Analise de Agua", parametros: "Zn,N,Mg", totalpagar: 1000, data: "2025-02-02 00:00", estado: "por analisar" },
	{ id: "a1e12", cliente: "c5", nome: "Analise de Agua", parametros: "Cn,Na,Mg", totalpagar: 1000, data: "2025-02-02 00:00", estado: "por analisar" },
];

export const analises = [
	{ id: "b1", proforma: "a11e", parametro: "Zn", valorfinal: 5284, data: "2025-02-02 00:00", x: 0, y: 0, z: 2 },
	{ id: "b2", proforma: "a111", parametro: "Na", valorfinal: 5284, data: "2025-02-02 00:00", x: 0, y: 0, z: 2 },
	{ id: "b3", proforma: "a111", parametro: "N", valorfinal: 5284, data: "2025-02-02 00:00", x: 0, y: 0, z: 2 },
	{ id: "b3", proforma: "a11e", parametro: "Mg", valorfinal: 5284, data: "2025-02-02 00:00", x: 0, y: 0, z: 2 },
	{ id: "b3", proforma: "a1e1", parametro: "Mg", valorfinal: 5284, data: "2025-02-02 00:00", x: 0, y: 0, z: 2 },
	{ id: "b3", proforma: "a1e1e", parametro: "Mg", valorfinal: 5284, data: "2025-02-02 00:00", x: 0, y: 0, z: 2 },
];

export const comprovativos = [
	{id: "212", proforma: "a11e", data: "2025-02-02 00:00"}
]

export const elementosQuimicos118 = [
    {id: "H", nome: "Hidrogênio", descricao: "Presente na água e em quase todos os compostos orgânicos."},
    {id: "He", nome: "Hélio", descricao: "Gás nobre usado em balões e ressonância magnética."},
    {id: "Li", nome: "Lítio", descricao: "Metal leve usado em baterias recarregáveis."},
    {id: "Be", nome: "Berílio", descricao: "Metal resistente usado em ligas e na indústria nuclear."},
    {id: "B", nome: "Boro", descricao: "Semimetal essencial em vidros e fertilizantes."},
    {id: "C", nome: "Carbono", descricao: "Base da química orgânica, presente em diamantes e grafite."},
    {id: "N", nome: "Nitrogênio", descricao: "Compõe 78% da atmosfera, essencial para a vida."},
    {id: "O", nome: "Oxigênio", descricao: "Fundamental para respiração e combustão."},
    {id: "F", nome: "Flúor", descricao: "Altamente reativo, usado em pastas de dente."},
    {id: "Ne", nome: "Neônio", descricao: "Gás nobre usado em letreiros luminosos."},
    {id: "Na", nome: "Sódio", descricao: "Metal reativo, comum no sal de cozinha."},
    {id: "Mg", nome: "Magnésio", descricao: "Usado em ligas leves e essencial para plantas."},
    {id: "Al", nome: "Alumínio", descricao: "Metal leve usado em embalagens e construções."},
    {id: "Si", nome: "Silício", descricao: "Base de semicondutores e materiais eletrônicos."},
    {id: "P", nome: "Fósforo", descricao: "Essencial para DNA e usado em fertilizantes."},
    {id: "S", nome: "Enxofre", descricao: "Usado em ácidos e compostos industriais."},
    {id: "Cl", nome: "Cloro", descricao: "Usado em desinfetantes e na produção de plásticos."},
    {id: "Ar", nome: "Argônio", descricao: "Gás nobre usado em soldagem e iluminação."},
    {id: "K", nome: "Potássio", descricao: "Essencial para funções celulares, presente em frutas."},
    {id: "Ca", nome: "Cálcio", descricao: "Fundamental para ossos e dentes."},
    {id: "Sc", nome: "Escândio", descricao: "Usado em ligas de alta resistência."},
    {id: "Ti", nome: "Titânio", descricao: "Metal forte usado em implantes e aeroespacial."},
    {id: "V", nome: "Vanádio", descricao: "Usado em aços de alta resistência."},
    {id: "Cr", nome: "Cromo", descricao: "Usado em aços inoxidáveis e cromagem."},
    {id: "Mn", nome: "Manganês", descricao: "Usado em ligas de aço e baterias."},
    {id: "Fe", nome: "Ferro", descricao: "Base do aço, essencial para a hemoglobina."},
    {id: "Co", nome: "Cobalto", descricao: "Usado em ligas magnéticas e baterias."},
    {id: "Ni", nome: "Níquel", descricao: "Usado em moedas e aços inoxidáveis."},
    {id: "Cu", nome: "Cobre", descricao: "Excelente condutor, usado em fios elétricos."},
    {id: "Zn", nome: "Zinco", descricao: "Usado em galvanização e suplementos."},
    {id: "Ga", nome: "Gálio", descricao: "Usado em semicondutores e LEDs."},
    {id: "Ge", nome: "Germânio", descricao: "Usado em eletrônicos e fibras ópticas."},
    {id: "As", nome: "Arsênio", descricao: "Usado em pesticidas e semicondutores."},
    {id: "Se", nome: "Selênio", descricao: "Essencial em pequenas quantidades, usado em eletrônicos."},
    {id: "Br", nome: "Bromo", descricao: "Usado em retardantes de chama e desinfetantes."},
    {id: "Kr", nome: "Criptônio", descricao: "Gás nobre usado em iluminação especial."},
    {id: "Rb", nome: "Rubídio", descricao: "Usado em relógios atômicos e pesquisa."},
    {id: "Sr", nome: "Estrôncio", descricao: "Usado em fogos de artifício e medicina."},
    {id: "Y", nome: "Ítrio", descricao: "Usado em lasers e supercondutores."},
    {id: "Zr", nome: "Zircônio", descricao: "Usado em reatores nucleares e joias."},
    {id: "Nb", nome: "Nióbio", descricao: "Usado em ligas de aço e supercondutores."},
    {id: "Mo", nome: "Molibdênio", descricao: "Usado em aços de alta resistência."},
    {id: "Tc", nome: "Tecnécio", descricao: "Radioativo, usado em diagnósticos médicos."},
    {id: "Ru", nome: "Rutênio", descricao: "Usado em catalisadores e eletrônicos."},
    {id: "Rh", nome: "Ródio", descricao: "Usado em catalisadores de automóveis."},
    {id: "Pd", nome: "Paládio", descricao: "Usado em conversores catalíticos e joias."},
    {id: "Ag", nome: "Prata", descricao: "Excelente condutor, usado em joias e eletrônicos."},
    {id: "Cd", nome: "Cádmio", descricao: "Usado em baterias e pigmentos."},
    {id: "In", nome: "Índio", descricao: "Usado em telas sensíveis ao toque e semicondutores."},
    {id: "Sn", nome: "Estanho", descricao: "Usado em soldas e revestimentos."},
    {id: "Sb", nome: "Antimônio", descricao: "Usado em ligas e retardantes de chama."},
    {id: "Te", nome: "Telúrio", descricao: "Usado em ligas e células solares."},
    {id: "I", nome: "Iodo", descricao: "Essencial para a tireoide, usado em antissépticos."},
    {id: "Xe", nome: "Xenônio", descricao: "Gás nobre usado em lâmpadas e propulsão iônica."},
    {id: "Cs", nome: "Césio", descricao: "Usado em relógios atômicos e fotossensores."},
    {id: "Ba", nome: "Bário", descricao: "Usado em raios X e fogos de artifício."},
    {id: "La", nome: "Lantânio", descricao: "Usado em baterias e catalisadores."},
    {id: "Ce", nome: "Cério", descricao: "Usado em polidores e catalisadores."},
    {id: "Pr", nome: "Praseodímio", descricao: "Usado em ímãs e óculos especiais."},
    {id: "Nd", nome: "Neodímio", descricao: "Usado em ímãs poderosos e lasers."},
    {id: "Pm", nome: "Promécio", descricao: "Radioativo, usado em dispositivos nucleares."},
    {id: "Sm", nome: "Samário", descricao: "Usado em ímãs e reatores nucleares."},
    {id: "Eu", nome: "Európio", descricao: "Usado em telas de TV e lâmpadas fluorescentes."},
    {id: "Gd", nome: "Gadolínio", descricao: "Usado em ressonância magnética e reatores."},
    {id: "Tb", nome: "Térbio", descricao: "Usado em lâmpadas e displays eletrônicos."},
    {id: "Dy", nome: "Disprósio", descricao: "Usado em ímãs e reatores nucleares."},
    {id: "Ho", nome: "Hólmio", descricao: "Usado em lasers e ímãs especiais."},
    {id: "Er", nome: "Érbio", descricao: "Usado em fibras ópticas e lasers."},
    {id: "Tm", nome: "Túlio", descricao: "Usado em equipamentos médicos e lasers."},
    {id: "Yb", nome: "Itérbio", descricao: "Usado em relógios atômicos e ligas."},
    {id: "Lu", nome: "Lutécio", descricao: "Usado em catalisadores e medicina nuclear."},
    {id: "Hf", nome: "Háfnio", descricao: "Usado em reatores nucleares e microchips."},
    {id: "Ta", nome: "Tântalo", descricao: "Usado em capacitores e implantes médicos."},
    {id: "W", nome: "Tungstênio", descricao: "Alta resistência, usado em filamentos e ligas."},
    {id: "Re", nome: "Rênio", descricao: "Usado em motores a jato e catalisadores."},
    {id: "Os", nome: "Ósmio", descricao: "Metal denso, usado em ligas e instrumentos."},
    {id: "Ir", nome: "Irídio", descricao: "Usado em velas de ignição e catalisadores."},
    {id: "Pt", nome: "Platina", descricao: "Usado em joias e catalisadores automotivos."},
    {id: "Au", nome: "Ouro", descricao: "Metal precioso, usado em joias e eletrônicos."},
    {id: "Hg", nome: "Mercúrio", descricao: "Líquido em temperatura ambiente, usado em termômetros."},
    {id: "Tl", nome: "Tálio", descricao: "Usado em eletrônicos e vidros especiais."},
    {id: "Pb", nome: "Chumbo", descricao: "Usado em baterias e proteção contra radiação."},
    {id: "Bi", nome: "Bismuto", descricao: "Usado em medicamentos e ligas de baixa fusão."},
    {id: "Po", nome: "Polônio", descricao: "Radioativo, usado em dispositivos antiestáticos."},
    {id: "At", nome: "Ástato", descricao: "Radioativo, estudado para tratamentos médicos."},
    {id: "Rn", nome: "Radônio", descricao: "Gás nobre radioativo, risco em ambientes fechados."},
    {id: "Fr", nome: "Frâncio", descricao: "Altamente radioativo, raro na natureza."},
    {id: "Ra", nome: "Rádio", descricao: "Radioativo, usado em tratamentos médicos históricos."},
    {id: "Ac", nome: "Actínio", descricao: "Radioativo, usado em pesquisas científicas."},
    {id: "Th", nome: "Tório", descricao: "Usado em reatores nucleares e ligas."},
    {id: "Pa", nome: "Protactínio", descricao: "Radioativo, usado em estudos científicos."},
    {id: "U", nome: "Urânio", descricao: "Usado em energia nuclear e armas."},
    {id: "Np", nome: "Neptúnio", descricao: "Radioativo, usado em detectores de nêutrons."},
    {id: "Pu", nome: "Plutônio", descricao: "Usado em armas nucleares e reatores."},
    {id: "Am", nome: "Amerício", descricao: "Usado em detectores de fumaça."},
    {id: "Cm", nome: "Cúrio", descricao: "Radioativo, usado em geradores termoelétricos."},
    {id: "Bk", nome: "Berquélio", descricao: "Radioativo, usado em pesquisas científicas."},
    {id: "Cf", nome: "Califórnio", descricao: "Usado em detectores e tratamentos médicos."},
    {id: "Es", nome: "Einstênio", descricao: "Radioativo, usado em estudos científicos."},
    {id: "Fm", nome: "Férmio", descricao: "Radioativo, produzido em laboratório."},
    {id: "Md", nome: "Mendelévio", descricao: "Radioativo, usado em pesquisas químicas."},
    {id: "No", nome: "Nobélio", descricao: "Radioativo, sintetizado em laboratório."},
    {id: "Lr", nome: "Laurêncio", descricao: "Radioativo, usado em estudos atômicos."},
    {id: "Rf", nome: "Rutherfórdio", descricao: "Sintético, estudado em química nuclear."},
    {id: "Db", nome: "Dúbnio", descricao: "Sintético, usado em pesquisas atômicas."},
    {id: "Sg", nome: "Seabórgio", descricao: "Sintético, estudado em laboratórios."},
    {id: "Bh", nome: "Bóhrio", descricao: "Sintético, usado em estudos químicos."},
    {id: "Hs", nome: "Hássio", descricao: "Sintético, pesquisado em física nuclear."},
    {id: "Mt", nome: "Meitnério", descricao: "Sintético, produzido em quantidades mínimas."},
    {id: "Ds", nome: "Darmstádtio", descricao: "Sintético, estudado em laboratórios."},
    {id: "Rg", nome: "Roentgênio", descricao: "Sintético, usado em pesquisas atômicas."},
    {id: "Cn", nome: "Copernício", descricao: "Sintético, estudado em química nuclear."},
    {id: "Nh", nome: "Nihônio", descricao: "Sintético, descoberto em laboratório."},
    {id: "Fl", nome: "Fleróvio", descricao: "Sintético, estudado em física nuclear."},
    {id: "Mc", nome: "Moscóvio", descricao: "Sintético, pesquisado em laboratórios."},
    {id: "Lv", nome: "Livermório", descricao: "Sintético, usado em estudos atômicos."},
    {id: "Ts", nome: "Tenessino", descricao: "Sintético, pesquisado em química nuclear."},
    {id: "Og", nome: "Oganessônio", descricao: "Sintético, elemento mais pesado conhecido."}
];